### ISSUE TITLE
RubyDep: WARNING: your Ruby is outdated/buggy. Please upgrade. (To disable warnings, set RUBY_DEP_GEM_SILENCE_WARNINGS=1)

### ISSUE THREAD

**Issue by chrishough** [rubyist/guard-rake#39]
I recently started getting this error when using this gem... ideas? `RubyDep: WARNING: your Ruby is outdated/buggy. Please upgrade. (To disable warnings, set RUBY_DEP_GEM_SILENCE_WARNINGS=1)`

**Comment by lamagnotti** [comment]
Same problem. I have no idea either!

**Comment by brunoocasali** [comment]
Same here, my version is:
```
[bruno@chp ~]$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
```

**Comment by brunoocasali** [comment]
Hey @chrishough and @lamagnotti, you should update your version of ruby to `2.3.1`. Then you will get no warnings!

**Comment by chrishough** [comment]
that fixed it for me, thank you
